In [3]:
import pandas as pd

names = pd.Series(["Ali", "Sara", "Ahmed", "Fatima"])
print("---Yeh aik series ha---")
print(names)

data={
    "Names": ["Ali", "Sara", "Ahmed", "Fatima"],
    "Ages": [25, 30, 22, 28],
    "Score": [85, 90, 78, 92]
}

df = pd.DataFrame(data)
print("---Yeh aik DataFrame ha---")
print(df)

---Yeh aik series ha---
0       Ali
1      Sara
2     Ahmed
3    Fatima
dtype: str
---Yeh aik DataFrame ha---
    Names  Ages  Score
0     Ali    25     85
1    Sara    30     90
2   Ahmed    22     78
3  Fatima    28     92

In [4]:
import pandas as pd

# Step A: Pehle hum khud aik choti si CSV file bana lete hain taake test kar sakein
data_to_save = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [1200, 25, 45, 300],
    "Stock": [10, 150, 80, 25]
}

# DataFrame banaya
temp_df = pd.DataFrame(data_to_save)

# Isko computer mein 'store_data.csv' ke naam se save kar diya
temp_df.to_csv("store_data.csv", index=False)
print("Choti si CSV file kamiyabi se ban gayi hai!")

# Step B: Ab asli jaadu - pd.read_csv() ke zariye us file ko wapas DataFrame mein lana!
df = pd.read_csv("store_data.csv")

print("\n--- CSV file ko read karne ke baad DataFrame ---")
display(df)

Choti si CSV file kamiyabi se ban gayi hai!

--- CSV file ko read karne ke baad DataFrame ---

    Product  Price  Stock
0    Laptop   1200     10
1     Mouse     25    150
2  Keyboard     45     80
3   Monitor    300     25

In [5]:
# Step 3: Memory Profiling - Yeh dekhna ke RAM kitni use ho rahi hai
print("--- DataFrame ki X-Ray Report (df.info) ---")
df.info()

--- DataFrame ki X-Ray Report (df.info) ---
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  4 non-null      str
 1   Price    4 non-null      int64
 2   Stock    4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 254.0 bytes

In [6]:
import pandas as pd
import numpy as np

# 1. Aisa data banate hain jisme kuch values gayab (NaN) hon
messy_data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "Price": [1200, 25, np.nan, 300, np.nan],  # Yahan 2 prices gayab hain (NaN)
    "Stock": [10, 150, 80, np.nan, 20]          # Yahan aik stock gayab hai
}

df_messy = pd.DataFrame(messy_data)
print("--- Khali data (Original Messy DataFrame) ---")
display(df_messy)

# 2. Yeh check karna ke kahan kahan data missing hai
print("\n--- Kahan kahan values missing hain? (isnull) ---")
display(df_messy.isnull())

# 3. Method A: dropna() - Jidhar bhi NaN ho, us poori row ko ura do
df_dropped = df_messy.dropna()
print("\n--- dropna() ke baad (Khali rows delete ho gayeen) ---")
display(df_dropped)

# 4. Method B: fillna() - Khali jagah par intelligent value dalna (Misal ke tor par Average Price)
mean_price = df_messy["Price"].mean()  # Price ka average nikala
df_filled = df_messy.copy()
df_filled["Price"] = df_filled["Price"].fillna(mean_price) # Khali price mein average daal diya
df_filled["Stock"] = df_filled["Stock"].fillna(0)          # Khali stock mein 0 daal diya

print("\n--- fillna() ke baad (Intelligently fix kiya gaya DataFrame) ---")
display(df_filled)

--- Khali data (Original Messy DataFrame) ---

    Product   Price  Stock
0    Laptop  1200.0   10.0
1     Mouse    25.0  150.0
2  Keyboard     NaN   80.0
3   Monitor   300.0    NaN
4   Printer     NaN   20.0

--- Kahan kahan values missing hain? (isnull) ---

   Product  Price  Stock
0    False  False  False
1    False  False  False
2    False   True  False
3    False  False   True
4    False   True  False

--- dropna() ke baad (Khali rows delete ho gayeen) ---

  Product   Price  Stock
0  Laptop  1200.0   10.0
1   Mouse    25.0  150.0

--- fillna() ke baad (Intelligently fix kiya gaya DataFrame) ---

    Product        Price  Stock
0    Laptop  1200.000000   10.0
1     Mouse    25.000000  150.0
2  Keyboard   508.333333   80.0
3   Monitor   300.000000    0.0
4   Printer   508.333333   20.0